spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    hikari:
      # use file based H2 so that we can attach with other tools
      # comment it out to use the default jdbc:h2:mem:testdb
      jdbc-url: jdbc:h2:./data/default
